"""create remaining tables

Revision ID: 64c0ec5c8d67
Revises: a3b349e22da0
Create Date: 2026-09-09 01:06:46.935522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c0ec5c8d67'
down_revision: Union[str, Sequence[str], None] = 'a3b349e22da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempts',
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('assessment_attempt_id')
    )
    op.create_index(op.f('ix_assessment_attempts_assessment_attempt_id'), 'assessment_attempts', ['assessment_attempt_id'], unique=False)
    op.create_table('learning_materials',
    sa.Column('learning_material_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('learning_material_id')
    )
    op.create_index(op.f('ix_learning_materials_learning_material_id'), 'learning_materials', ['learning_material_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('learning_path_id')
    )
    op.create_index(op.f('ix_learning_paths_learning_path_id'), 'learning_paths', ['learning_path_id'], unique=False)
    op.create_table('topic_mastery',
    sa.Column('topic_mastery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('weak_areas', sa.JSON(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('topic_mastery_id')
    )
    op.create_index(op.f('ix_topic_mastery_topic_mastery_id'), 'topic_mastery', ['topic_mastery_id'], unique=False)
    op.create_table('topic_prerequisites',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'prerequisite_topic_id')
    )
    op.create_table('assessment_responses',
    sa.Column('assessment_response_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('learner_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score_awarded', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.assessment_attempt_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('assessment_response_id')
    )
    op.create_index(op.f('ix_assessment_responses_assessment_response_id'), 'assessment_responses', ['assessment_response_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.learning_path_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    op.create_index(op.f('ix_chat_sessions_chat_session_id'), 'chat_sessions', ['chat_session_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('learning_path_item_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.learning_path_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('learning_path_item_id')
    )
    op.create_index(op.f('ix_learning_path_items_learning_path_item_id'), 'learning_path_items', ['learning_path_item_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_action', sa.String(length=20), nullable=True),
    sa.Column('retrieved_sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.chat_session_id'], ),
    sa.PrimaryKeyConstraint('chat_message_id')
    )
    op.create_index(op.f('ix_chat_messages_chat_message_id'), 'chat_messages', ['chat_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_chat_message_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_learning_path_items_learning_path_item_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_chat_sessions_chat_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_assessment_responses_assessment_response_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_table('topic_prerequisites')
    op.drop_index(op.f('ix_topic_mastery_topic_mastery_id'), table_name='topic_mastery')
    op.drop_table('topic_mastery')
    op.drop_index(op.f('ix_learning_paths_learning_path_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_learning_materials_learning_material_id'), table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index(op.f('ix_assessment_attempts_assessment_attempt_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    # ### end Alembic commands ###
